"""
Linear MPC benchmark for hyperparameter search.

This file defines a simple constrained linear tracking problem that is more
appropriate than neural-policy distillation if the goal is to optimize MPC
hyperparameters directly.

The benchmark exposes a few design knobs that an optimizer/agent can tune:
    - prediction horizon
    - state tracking weights
    - control effort weight
    - control variation weight
    - terminal cost multiplier

The returned objective is a single scalar to MINIMIZE. Lower is better.

Usage:
    uv run linear_mpc_problem.py
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

import torch


# ---------------------------------------------------------------------------
# Fixed benchmark settings
# ---------------------------------------------------------------------------

DTYPE = torch.float64
DT = 0.2
STATE_DIM = 4
CONTROL_DIM = 1
ROLLOUT_STEPS = 40
NUM_SCENARIOS = 9

# Hard constraints used in the closed-loop simulation.
CONTROL_LIMIT = 1.0
POSITION_LIMIT = 3.0
VELOCITY_LIMIT = 2.5

# Fixed outer-loop evaluation weights. These stay constant across experiments so
# hyperparameter search cannot improve the score just by redefining the metric.
EVAL_POSITION_WEIGHT = 8.0
EVAL_VELOCITY_WEIGHT = 1.5
EVAL_CONTROL_WEIGHT = 0.15
EVAL_DELTA_U_WEIGHT = 0.35
EVAL_TERMINAL_MULTIPLIER = 3.0

# Fixed plant: double integrator with a constant disturbance state.
A = torch.tensor([
    [1.0, DT, 0.0, 0.0],
    [0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, DT],
    [0.0, 0.0, 0.0, 1.0],
], dtype=DTYPE)
B = torch.tensor([
    [0.5 * DT * DT],
    [DT],
    [0.0],
    [0.0],
], dtype=DTYPE)

# The third state is an exogenous reference position generated by a simple
# linear model, and the fourth state is its velocity. Tracking is performed
# against x_ref = [reference_position, reference_velocity].


# ---------------------------------------------------------------------------
# Hyperparameters to tune
# ---------------------------------------------------------------------------


@dataclass
class MPCParams:
    horizon: int = 6
    position_weight: float = 7.0
    velocity_weight: float = 2.3
    control_weight: float = 0.28
    delta_u_weight: float = 0.65
    terminal_multiplier: float = 1.6


# ---------------------------------------------------------------------------
# Benchmark scenarios
# ---------------------------------------------------------------------------


def build_scenarios() -> torch.Tensor:
    """Create deterministic initial states for fair hyperparameter comparison."""
    scenarios = torch.tensor([
        [-2.5, 0.0, 0.0, 0.0],
        [2.2, 0.0, 0.0, 0.0],
        [-1.5, -0.8, 1.0, 0.0],
        [1.5, 0.9, -1.0, 0.0],
        [0.5, -1.2, 1.5, 0.2],
        [-0.5, 1.1, -1.5, -0.2],
        [-2.0, 0.5, 2.0, 0.0],
        [2.0, -0.5, -2.0, 0.0],
        [0.0, 0.0, 0.0, 0.0],
    ], dtype=DTYPE)
    if scenarios.size(0) != NUM_SCENARIOS:
        raise ValueError("NUM_SCENARIOS does not match the scenario table.")
    return scenarios


SCENARIOS = build_scenarios()


# ---------------------------------------------------------------------------
# MPC machinery
# ---------------------------------------------------------------------------


def validate_params(params: MPCParams) -> None:
    if params.horizon < 2:
        raise ValueError("horizon must be >= 2")
    positive = {
        "position_weight": params.position_weight,
        "velocity_weight": params.velocity_weight,
        "control_weight": params.control_weight,
        "delta_u_weight": params.delta_u_weight,
        "terminal_multiplier": params.terminal_multiplier,
    }
    for name, value in positive.items():
        if value <= 0.0:
            raise ValueError(f"{name} must be > 0, got {value}")


def make_augmented_system() -> tuple[torch.Tensor, torch.Tensor]:
    """
    Augment the system with the previous control so we can penalize delta-u
    while still solving an LQR-style linear quadratic problem.
    """
    a_aug = torch.zeros(STATE_DIM + CONTROL_DIM, STATE_DIM + CONTROL_DIM, dtype=DTYPE)
    b_aug = torch.zeros(STATE_DIM + CONTROL_DIM, CONTROL_DIM, dtype=DTYPE)

    a_aug[:STATE_DIM, :STATE_DIM] = A
    a_aug[:STATE_DIM, STATE_DIM:] = B
    a_aug[STATE_DIM:, STATE_DIM:] = torch.eye(CONTROL_DIM, dtype=DTYPE)

    b_aug[:STATE_DIM, :] = B
    b_aug[STATE_DIM:, :] = torch.eye(CONTROL_DIM, dtype=DTYPE)
    return a_aug, b_aug


def make_cost_matrices(params: MPCParams) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Penalize tracking error on [position, velocity] plus the increment in the
    control action. The disturbance/reference states are not directly penalized.
    """
    q = torch.diag(torch.tensor([
        params.position_weight,
        params.velocity_weight,
        0.0,
        0.0,
        params.delta_u_weight,
    ], dtype=DTYPE))
    r = torch.diag(torch.tensor([params.control_weight], dtype=DTYPE))
    qf = params.terminal_multiplier * q
    return q, r, qf


def finite_horizon_lqr_gain(
    a: torch.Tensor,
    b: torch.Tensor,
    q: torch.Tensor,
    r: torch.Tensor,
    qf: torch.Tensor,
    horizon: int,
) -> list[torch.Tensor]:
    p = qf.clone()
    gains: list[torch.Tensor] = []
    for _ in range(horizon):
        gram = r + b.T @ p @ b
        k = torch.linalg.solve(gram, b.T @ p @ a)
        gains.append(k)
        p = q + a.T @ p @ (a - b @ k)
    gains.reverse()
    return gains


def make_tracking_error_state(x: torch.Tensor, previous_u: torch.Tensor) -> torch.Tensor:
    """
    The optimization state is built on the tracking error relative to the
    time-varying reference embedded in the last two states.
    """
    error = torch.empty(STATE_DIM + CONTROL_DIM, dtype=DTYPE)
    error[0] = x[0] - x[2]
    error[1] = x[1] - x[3]
    error[2] = 0.0
    error[3] = 0.0
    error[4] = previous_u
    return error


def clamp_state(x: torch.Tensor) -> tuple[torch.Tensor, float]:
    """Apply hard bounds and return the amount of violation before clamping."""
    raw_position_violation = torch.clamp(x[0].abs() - POSITION_LIMIT, min=0.0).item()
    raw_velocity_violation = torch.clamp(x[1].abs() - VELOCITY_LIMIT, min=0.0).item()
    x_next = x.clone()
    x_next[0] = torch.clamp(x_next[0], -POSITION_LIMIT, POSITION_LIMIT)
    x_next[1] = torch.clamp(x_next[1], -VELOCITY_LIMIT, VELOCITY_LIMIT)
    return x_next, raw_position_violation + raw_velocity_violation


def simulate_closed_loop(params: MPCParams) -> dict[str, float]:
    validate_params(params)
    a_aug, b_aug = make_augmented_system()
    q, r, qf = make_cost_matrices(params)
    gains = finite_horizon_lqr_gain(a_aug, b_aug, q, r, qf, params.horizon)
    k0 = gains[0]

    total_tracking_cost = 0.0
    total_control_cost = 0.0
    total_slew_cost = 0.0
    total_constraint_violation = 0.0
    terminal_tracking_cost = 0.0

    for initial_state in SCENARIOS:
        x = initial_state.clone()
        previous_u = torch.zeros(1, dtype=DTYPE)

        for _ in range(ROLLOUT_STEPS):
            error_state = make_tracking_error_state(x, previous_u)
            delta_u = -(k0 @ error_state.unsqueeze(1)).squeeze(1)
            u = torch.clamp(previous_u + delta_u, -CONTROL_LIMIT, CONTROL_LIMIT)
            applied_delta_u = u - previous_u

            tracking_error = torch.tensor([x[0] - x[2], x[1] - x[3]], dtype=DTYPE)
            total_tracking_cost += (
                EVAL_POSITION_WEIGHT * tracking_error[0].pow(2).item()
                + EVAL_VELOCITY_WEIGHT * tracking_error[1].pow(2).item()
            )
            total_control_cost += EVAL_CONTROL_WEIGHT * u.pow(2).sum().item()
            total_slew_cost += EVAL_DELTA_U_WEIGHT * applied_delta_u.pow(2).sum().item()

            x = A @ x + B @ u
            x, raw_violation = clamp_state(x)
            total_constraint_violation += raw_violation
            previous_u = u

        final_tracking_error = torch.tensor([x[0] - x[2], x[1] - x[3]], dtype=DTYPE)
        terminal_tracking_cost += EVAL_TERMINAL_MULTIPLIER * (
            EVAL_POSITION_WEIGHT * final_tracking_error[0].pow(2).item()
            + EVAL_VELOCITY_WEIGHT * final_tracking_error[1].pow(2).item()
        )

    normalizer = float(NUM_SCENARIOS * ROLLOUT_STEPS)
    objective = (
        total_tracking_cost
        + total_control_cost
        + total_slew_cost
        + terminal_tracking_cost
        + 500.0 * total_constraint_violation
    ) / normalizer

    return {
        "objective": objective,
        "tracking_cost": total_tracking_cost / normalizer,
        "control_cost": total_control_cost / normalizer,
        "slew_cost": total_slew_cost / normalizer,
        "terminal_cost": terminal_tracking_cost / normalizer,
        "constraint_violation": total_constraint_violation / normalizer,
    }


def evaluate_hyperparameters(params: MPCParams) -> float:
    """Main scalar objective for outer-loop optimization. Lower is better."""
    return simulate_closed_loop(params)["objective"]


def main() -> None:
    params = MPCParams()
    metrics = simulate_closed_loop(params)

    print("Linear MPC benchmark")
    print(f"params: {asdict(params)}")
    print("---")
    for key, value in metrics.items():
        print(f"{key}: {value:.6f}")


if __name__ == "__main__":
    main()
